version: '3'

services:
  mongo:
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ADMIN
      MONGO_INITDB_ROOT_PASSWORD: admin_pass
    ports:
      - 27017:27017
  express:
    image: mongo-express:0.54
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ADMIN
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin_pass
      ME_CONFIG_MONGODB_URL: mongodb://ADMIN:admin_pass@mongo:27017/