version: '3'

services:
  kube-news:
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      DB_DATABASE: postgres
      DB_USERNAME: ADMIN
      DB_PASSWORD: admin_pass
      DB_HOST: postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_PASSWORD: admin_pass
      POSTGRES_USER: ADMIN
  pgAdmin:
    image: dpage/pgadmin4:6.18
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: arthurgnascto@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin_pass
    ports:
      - 80:80